spring.application.name=clienteseguridad


client.ssl.trust-store=C:\\Users\\MSI\\Desktop\\Programacion\\Universidad\\7semestre\\Patrones\\3er corte\\mtls\\clienteseguridad\\src\\main\\resources\\truststore-client.jks
client.ssl.trust-store-password=changeit
client.ssl.one-way-authentication-enabled= false
client.ssl.two-way-authentication-enabled= true

server.port=8074
client.ssl.key-store= classpath:identity.jks
client.ssl.key-store-password= changeme
client.ssl.key-password= changeme
client.ssl.key-store-type= JKS
client.ssl.key-alias= cliente1.bancofachero (bancofachero-root-ca)


