spring.application.name=clienteseguridad


client.ssl.trust-store=C:\\Users\\LENOVO\\Documents\\Trabajos U.sabana\\7sem\\patrones\\certificado autofirmado\\clienteseguridad\\src\\main\\resources\\truststore-client.jks
client.ssl.trust-store-password=changeit
client.ssl.one-way-authentication-enabled=false
client.ssl.two-way-authentication-enabled=true


server.port=8074 
client.ssl.key-store: classpath:identity.jks
client.ssl.key-store-password: changeit
client.ssl.key-password: changeit
client.ssl.key-store-type=JKS
client.ssl.key-alias=client


