spring.application.name=seguridad

server.ssl.enabled=true
server.ssl.key-store=classpath:identity.jks
server.ssl.key-password= changeit
server.ssl.key-store-password= changeit

server.port=8075
server.ssl.client-auth=need
server.ssl.trust-store=classpath:truststore-server.jks
server.ssl.trust-store-password=changeit


